### ISSUE TITLE
Some Pull requests

### ISSUE THREAD

**Issue by LinusDietz** [whatever4711/cookbook#23]
Dear Maintainers,
on behalf of many excellent people I am happy to request their delicious recipes to be merged into the master branch of this extraordinary collection of recipes.

(:

**Comment by whatever4711** [comment]
Dear Lynyus,

thanks for your effort and the many delicious recipes. Hopefully, we are enriching them with some pictures in the near future. Stay tuned.
Moreover, thank you all for this extraordinary collection of delicious food from all of our friends and family

(:
